repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-cognitive-complexity
          - flake8-functions
        args: ["--select=CCR,CFQ", "--max-cognitive-complexity=15", "--max-returns-amount=3"]
        files: ^src/

  - repo: local
    hooks:
      - id: doxygen-guard
        name: doxygen-guard
        entry: .venv/bin/doxygen-guard
        language: system
        types: [python]
        files: ^src/

      - id: pytest
        name: pytest
        entry: .venv/bin/pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
